# -*- coding: utf-8 -*-
"""6.4 Semantic Index

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYoIMe3JcRfVoO-VEEOE_iWLvfVXIbir
"""

# Installing the necessary libraries
!pip install datasets==2.14.0
!pip install torch[cpu]
!pip install sentence-transformers==2.2.2

"""### 📚 Step 1: Import Libraries

First, let's import the necessary libraries that will empower us to manipulate datasets, process text, and perform mathematical operations.
"""

from datasets import load_dataset
from sentence_transformers import SentenceTransformer, util
import torch
import os

"""### 🗂️ Step 2: Load the Dataset

We load the multi_news dataset, focusing on the 'test' split to efficiently manage our resources.
"""

dataset = load_dataset("multi_news", split="test")
dataset

"""### 📊 Step 3: Data Preparation

To ensure our analysis is manageable and efficient, we'll focus on a subset of 2000 random samples from our dataset.
"""

df = dataset.to_pandas().sample(2000, random_state=42)
df

"""### 🧠 Step 4: Load the Model

Next, we load a pre-trained Sentence Transformer model. This model will help us convert textual data into dense vectors (embeddings) that capture the essence of our text.
"""

model = SentenceTransformer("all-MiniLM-L6-v2")
model

"""### 🔍 Step 5: Generate Embeddings

Here, we encode the article summaries into embeddings, transforming the textual information into a numerical format that's easier to analyze.
"""

passage_embeddings = list(model.encode(df['summary'].to_list(), show_progress_bar=True))
passage_embeddings[0].shape

"""### 🎯 Step 6: Define a Query

Let's specify a query for which we want to find relevant articles. This will be our target for similarity searches.
"""

query = "Find me some articles about technology and artificial intelligence"

"""### 📏 Step 7: Find Relevant Articles

To find articles that match our query, we compute the cosine similarity between the query embedding and all article embeddings, retrieving the top 3 most relevant articles.
"""

query_embedding = model.encode(query)
similarities = util.cos_sim(query_embedding, passage_embeddings)

top_indices = torch.topk(similarities.flatten(), 3).indices
top_relevant_passages = [df.iloc[x.item()]['summary'][:200] + "..." for x in top_indices]
top_relevant_passages

"""### 🛠️ Utility Function: Find Relevant News

To simplify the process of finding relevant articles for any query, we encapsulate our code in a function. This function takes a query, processes it, and returns the top 3 relevant articles.
"""

def find_relevant_news(query):
    # Encode the query using the same model
    query_embedding = model.encode(query)

    # Calculate the cosine similarity between the query and passage embeddings
    similarities = util.cos_sim(query_embedding, passage_embeddings)

    # Get the indices of the top 3 most similar passages
    top_indices = torch.topk(similarities.flatten(), 3).indices

    # Retrieve the summaries of the top 3 passages and truncate them to 160 characters
    top_relevant_passages = [df.iloc[x.item()]["summary"][:160] + "..." for x in top_indices]

    return top_relevant_passages

"""### 📈 Conclusion & Next Steps

This notebook illustrates the power of NLP in extracting relevant information from large text datasets using sentence embeddings and cosine similarity. Explore further by modifying the query or adjusting the function to suit different needs. Happy coding! 🌟
"""

# Example queries to explore
print(find_relevant_news("Natural disasters"))
print(find_relevant_news("Law enforcement and police"))
print(find_relevant_news("Politics, diplomacy and nationalism"))

def clear_screen():
    os.system("clear")

def interactive_search():
    print("Welcome to the Semantic News Search!\n")
    while True:
        print("Type in a topic you'd like to find articles about, and I'll do the searching! (Type 'exit' to quit)\n> ", end="")

        query = input().strip()

        if query.lower() == "exit":
            print("\nThanks for using the Semantic News Search! Have a great day!")
            break

        print("\n\tHere are 3 articles I found based on your query: \n")

        passages = find_relevant_news(query)
        for passage in passages:
            print("\n\t" + passage)

        input("\nPress Enter to continue searching...")
        clear_screen()

# Start the interactive search
interactive_search()

