# -*- coding: utf-8 -*-
"""6.3 Masked Language Modeling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMpEYowE4RsupsSN3m0lw4Vn1G-TgGgD

# 🎭 **Masked Language Modeling with BERT**

Explore masked language modeling (MLM) using the BERT model to understand context and predict missing words in sentences.

## 🛠️ Setup and Installation

Begin by installing the necessary libraries to manage data processing and modeling.
"""

!pip install -U transformers

"""## 📚 Importing Libraries

Import essential modules for our tasks.
"""

from transformers import AutoModelForMaskedLM, AutoTokenizer
import pandas as pd
import numpy as np
from scipy.special import softmax

"""## 🤖 Model Setup

Load the pre-trained BERT model and tokenizer, specifically designed for masked language modeling.
"""

model_name = "bert-base-cased"

# Loading the pre-trained model and tokenizer
model = AutoModelForMaskedLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

"""## 🎭 Defining the Mask Token

Identify the mask token used by BERT to signify where predictions are needed in the sentence.

## ✏️ Creating the Input Sentence

Craft a sentence with a missing word indicated by the mask token, to test the model's predictive power.
"""

# Defining the mask token
mask = tokenizer.mask_token

# Defining the sentence
sentence = f"I want to {mask} pizza for tonight."

# Tokenizing the sentence
tokens = tokenizer.tokenize(sentence)

sentence

mask, tokens

len(tokens)

"""## 🔍 Tokenization and Encoding

Tokenize and encode the sentence to format it properly for the model.

## 📈 Model Prediction

Feed the encoded inputs to the model and extract logits for predictions.
"""

# Encoding the input sentence and getting model predictions
encoded_inputs = tokenizer(sentence, return_tensors="pt")
output = model(**encoded_inputs)

# Detaching the logits from the model output and converting to numpy array
logits = output.logits.detach().numpy()[0]

output.logits.shape

output.logits.detach()

output.logits.detach().numpy()

"""
## 🔎 Analyzing Predictions

Retrieve logits for the masked token and calculate confidence scores for possible replacements."""

logits.shape

tokens.index(mask)

logits[tokens.index(mask) + 1]

# Extracting the logits for the masked token and calculating the confidence scores
masked_logits = logits[tokens.index(mask) + 1]
confidence_scores = softmax(masked_logits)

confidence_scores

confidence_scores.sum()

"""## 📝 Displaying Top Predictions

Cycle through the top 5 predicted tokens, substituting the masked token in the original sentence to show the model's suggestions.

"""

np.argsort(confidence_scores)

np.argsort(confidence_scores)[::-1]

confidence_scores[np.argsort(confidence_scores)[::-1]]

confidence_scores[np.argsort(confidence_scores)[::-1][:5]]

# Iterating over the top 5 predicted tokens and printing the sentences with the masked token replaced
for token_id in np.argsort(confidence_scores)[::-1][:5]:
    pred_token = tokenizer.decode(token_id)
    score = confidence_scores[token_id]
    print('Token ID: {}, Pred Token: {}, Confidence score: {}'.format(token_id, pred_token, score))

    # print(pred_token, score)
    print(sentence.replace(mask, pred_token))